item { 
	name:'bolt'
	id:1
}
item { 
	name:'concrete'
	id:2
}
item { 
	name:'nut'
	id:3
}
item { 
	name:'pliers'
	id:4
}
item { 
	name:'screwdriver'
	id:5
}
item { 
	name:'wood'
	id:6
}
item { 
	name:'wrench'
	id:7
}
